name: plantuml
on:
  push:
    paths:
      - '**.puml'
    branches:
      - master
permissions:
  contents: write
jobs:
  plantuml:
    runs-on: macos-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg diagrams/*.puml
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: nqbu
          author_email: ponevaj@gmail.com
          message: 'diagram generated'
          # destination folder
          add: 'diagrams/*'
